### PR TITLE
Round edges

### PR DESCRIPTION
**Pull request by michaelni678**
rounded the edges on some of the cards by 5px

### CODE REVIEW

**Comment by michaelni678** [comment]
Closes #20

**Comment by anderm18** [comment]
Good Job : )

**Comment by anderm18** [comment]
Can you stash the changes of package-lock.json? It's making netlify mad (this isnt your fault, Desktop probably detected changes when u ran npm install and tried to commit them)

**Comment by anderm18** [comment]
Closing this PR; I took care of it by committing your changes separately. If you see that package-lock.json got caught in your GitHub Desktop commit, just uncheck it unless you actually want it to change.

Just link to this  commit in your Status Update, as this obviously is your commit and I marked it as so

https://github.com/anderm18/HASSPathways/commit/3f259bc42773e4a143707cab0f0d433f33444827

**Pull request closed without merging**
